// Generated by tools/img2lvgl.py from res/monero.png - do not edit.
#pragma once
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

#if LVGL_VERSION_MAJOR >= 9
extern const lv_image_dsc_t mw_img_monero_96;
extern const lv_image_dsc_t mw_img_monero_160;
extern const lv_image_dsc_t mw_img_monero_256;
// Every size above, smallest first (MW_IMG_MONERO_COUNT entries).
extern const lv_image_dsc_t* const mw_img_monero_all[];
#endif

// Sizes, smallest first.
#define MW_IMG_MONERO_SIZES { 96, 160, 256 }
#define MW_IMG_MONERO_COUNT 3

#ifdef __cplusplus
}
#endif
