#!/usr/bin/env python3
"""Regenerate src/data/wordlist_*.h from the upstream sources.

    python3 tools/gen_wordlists.py [--offline DIR]

Downloads (or reads from DIR) the two upstream wordlists, verifies their
invariants, and emits the C headers. The invariants are what the on-screen
keyboard relies on, so a failure here is a hard error, not a warning.

Sources:
  Monero legacy : monero-project/monero  src/mnemonics/english.h   (BSD-3-Clause)
  Polyseed      : tevador/polyseed       src/lang_en.c             (Apache-2.0)
"""
import argparse
import os
import re
import sys
import urllib.request

MONERO_URL = ("https://raw.githubusercontent.com/monero-project/monero/"
              "master/src/mnemonics/english.h")
POLYSEED_URL = ("https://raw.githubusercontent.com/tevador/polyseed/"
                "master/src/lang_en.c")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "data")


def fetch(url, offline_dir, name):
    if offline_dir:
        with open(os.path.join(offline_dir, name), encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def check_unique_prefixes(words, n, label):
    seen = {}
    for w in words:
        k = w[:n]
        if k in seen:
            raise SystemExit(
                f"{label}: prefix {k!r} is shared by {w!r} and {seen[k]!r}")
        seen[k] = w


def emit(path, guard, name, words, prefix_len, note):
    with open(path, "w") as f:
        f.write(f"// {note}\n")
        f.write("// Auto-generated by tools/gen_wordlists.py - "
                "DO NOT EDIT BY HAND.\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write('#include <stdint.h>\n#include "wordlist.h"\n\n')
        f.write(f"#define {name.upper()}_COUNT {len(words)}\n")
        f.write(f"#define {name.upper()}_PREFIX_LEN {prefix_len}\n\n")
        f.write(f"MW_WORDLIST_STORAGE const char* const "
                f"{name}_words[{len(words)}] = {{\n")
        for i in range(0, len(words), 8):
            f.write("    " + " ".join(f'"{w}",' for w in words[i:i + 8]) + "\n")
        f.write("};\n\n#endif\n")
    print(f"wrote {path} ({len(words)} words)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", metavar="DIR",
                    help="read english.h and lang_en.c from DIR instead of "
                         "downloading")
    args = ap.parse_args()

    src = fetch(MONERO_URL, args.offline, "english.h")
    monero = re.findall(r'"([a-z]+)"', src)
    if len(monero) != 1626:
        raise SystemExit(f"Monero wordlist: expected 1626 words, got "
                         f"{len(monero)}")
    check_unique_prefixes(monero, 3, "Monero")

    src = fetch(POLYSEED_URL, args.offline, "lang_en.c")
    body = src.split(".words = {", 1)[1]
    poly = re.findall(r'"([a-z]+)"', body)
    if len(poly) != 2048:
        raise SystemExit(f"Polyseed wordlist: expected 2048 words, got "
                         f"{len(poly)}")
    if poly != sorted(poly):
        raise SystemExit("Polyseed wordlist must be sorted (binary search "
                         "depends on it)")
    check_unique_prefixes(poly, 4, "Polyseed")

    os.makedirs(OUT, exist_ok=True)
    emit(os.path.join(OUT, "wordlist_monero_en.h"),
         "MW_WORDLIST_MONERO_EN_H", "monero_en", monero, 3,
         "Monero legacy (25-word) English wordlist, 1626 words. "
         "Source: monero-project/monero src/mnemonics/english.h "
         "(BSD-3-Clause).")
    emit(os.path.join(OUT, "wordlist_polyseed_en.h"),
         "MW_WORDLIST_POLYSEED_EN_H", "polyseed_en", poly, 4,
         "Polyseed English wordlist, 2048 words (BIP-39 derived). "
         "Source: tevador/polyseed src/lang_en.c (Apache-2.0 / MIT).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
