#!/usr/bin/env python3
"""PNG -> LVGL 9 C images (RGB565A8), one per size.

    python tools/img2lvgl.py res/monero.png src/ui/img_monero mw_img_monero 160

writes img_monero.c / img_monero.h with `const lv_image_dsc_t mw_img_monero_96`
etc. The picture is cropped to its visible part (alpha > 0), centred on a
square canvas and downscaled with Lanczos in premultiplied alpha (no dark
fringe). Never upscaled: a size larger than the source is skipped.
Needs Pillow (pip install pillow).
"""
import sys
from PIL import Image


def prepare(path):
    im = Image.open(path).convert("RGBA")
    box = im.getchannel("A").getbbox() or (0, 0, im.width, im.height)
    im = im.crop(box)
    side = max(im.size)
    sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    sq.paste(im, ((side - im.width) // 2, (side - im.height) // 2))
    return sq


def scaled(sq, n):
    return sq.convert("RGBa").resize((n, n), Image.LANCZOS).convert("RGBA")


def rgb565a8(im):
    raw = im.tobytes()
    colour = bytearray()
    alpha = bytearray()
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        colour += bytes((v & 0xFF, v >> 8))          # little-endian RGB565
        alpha.append(a)
    return bytes(colour + alpha)


def c_array(data):
    lines = []
    for i in range(0, len(data), 24):
        lines.append("    " + ",".join("0x%02x" % b for b in data[i:i + 24]) + ",")
    return "\n".join(lines)


def main():
    if len(sys.argv) < 5:
        sys.exit(__doc__)
    src, out, name = sys.argv[1], sys.argv[2], sys.argv[3]
    sizes = sorted(int(x) for x in sys.argv[4:])
    sq = prepare(src)
    sizes = [n for n in sizes if n <= sq.width]
    base = out.replace("\\", "/").split("/")[-1]
    c = ["// Generated by tools/img2lvgl.py from %s - do not edit." % src.replace("\\", "/"),
         '#include "%s.h"' % base, "", "#if LVGL_VERSION_MAJOR >= 9     // lv_image_dsc_t of LVGL 9", ""]
    h = ["// Generated by tools/img2lvgl.py from %s - do not edit." % src.replace("\\", "/"),
         "#pragma once", "#include <lvgl.h>", "", "#ifdef __cplusplus", 'extern "C" {',
         "#endif", "", "#if LVGL_VERSION_MAJOR >= 9"]
    for n in sizes:
        data = rgb565a8(scaled(sq, n))
        c += ["static const uint8_t %s_%d_map[] = {" % (name, n), c_array(data), "};", "",
              "const lv_image_dsc_t %s_%d = {" % (name, n),
              "    .header = {",
              "        .magic = LV_IMAGE_HEADER_MAGIC,",
              "        .cf = LV_COLOR_FORMAT_RGB565A8,",
              "        .flags = 0,",
              "        .w = %d," % n,
              "        .h = %d," % n,
              "        .stride = %d," % (n * 2),
              "    },",
              "    .data_size = sizeof(%s_%d_map)," % (name, n),
              "    .data = %s_%d_map," % (name, n),
              "};", ""]
        h.append("extern const lv_image_dsc_t %s_%d;" % (name, n))
    c += ["// Every size, smallest first.",
          "const lv_image_dsc_t* const %s_all[%s_COUNT] = {" % (name, name.upper()),
          "    " + ", ".join("&%s_%d" % (name, n) for n in sizes) + ",", "};", "",
          "#endif", ""]
    h += ["// Every size above, smallest first (%s_COUNT entries)." % name.upper(),
          "extern const lv_image_dsc_t* const %s_all[];" % name,
          "#endif", "", "// Sizes, smallest first.", "#define %s_SIZES { %s }" % (name.upper(), ", ".join(map(str, sizes))),
          "#define %s_COUNT %d" % (name.upper(), len(sizes)), "",
          "#ifdef __cplusplus", "}", "#endif", ""]
    open(out + ".c", "w", newline="\n").write("\n".join(c))
    open(out + ".h", "w", newline="\n").write("\n".join(h))
    print("wrote %s.c/.h: %s" % (out, ", ".join("%dpx" % n for n in sizes)))


if __name__ == "__main__":
    main()
